// Build the server-side content assets in src/lib/server/content/ from tool/raw/.
// Run with: npm run content:prepare  (deterministic: re-running must not change any output)
import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import wordListPath from 'word-list';
import { buildFormIndex, buildNgsl, parseLemmatized, parseStats } from './lib/ngsl.ts';
import { generatePseudowords, parseExcludeList } from './lib/pseudowords.ts';
import { filterPairs, toItems } from './lib/tatoeba.ts';
import { parsePairsTsv } from './lib/tatoeba-pairs.ts';
import { contentFile, toJson } from './lib/text.ts';

const PSEUDOWORD_COUNT = 120;
const PSEUDOWORD_SEED = 20261002;

const TOOL = import.meta.dirname;
const RAW = join(TOOL, 'raw');
const OUT = join(TOOL, '..', 'src', 'lib', 'server', 'content');
const read = (path: string) => readFileSync(path, 'utf8');

function write(path: string, contents: string): void {
	writeFileSync(path, contents);
	console.log(`wrote ${path}`);
}

// --- NGSL -------------------------------------------------------------------------------------
const ngsl = buildNgsl(
	parseStats(read(join(RAW, 'NGSL_1.2_stats.csv'))),
	parseLemmatized(read(join(RAW, 'NGSL_1.2_lemmatized_for_research.csv')), 'NGSL lemmatized'),
	parseLemmatized(read(join(RAW, 'SUP_lemmatized.csv')), 'NGSL supplementary')
);
write(join(OUT, 'ngsl.json'), toJson({
	...contentFile(
		{
			source: 'New General Service List 1.2 (newgeneralservicelist.com): NGSL_1.2_stats.csv, NGSL_1.2_lemmatized_for_research.csv, SUP_lemmatized.csv',
			license: 'CC BY-SA 4.0 (https://creativecommons.org/licenses/by-sa/4.0/)',
			attribution: 'Browne, C., Culligan, B., & Phillips, J. (2013). The New General Service List. www.newgeneralservicelist.com'
		},
		ngsl.items
	),
	supplementary: ngsl.supplementary
}));
console.log(`NGSL: ${ngsl.items.length} ranked headwords, ${ngsl.supplementary.length} supplementary, ${ngsl.formCount} forms`);
console.log(`NGSL cross-check: stats only [${ngsl.statsOnly.join(', ')}], lemmatized only [${ngsl.lemmatizedOnly.join(', ')}]`);
console.log(`NGSL supplementary words that are also ranked: [${ngsl.supplementaryAlsoRanked.join(', ')}]`);

// --- Tatoeba ----------------------------------------------------------------------------------
const formIndex = buildFormIndex(ngsl.items, ngsl.supplementary);
const filtered = filterPairs(parsePairsTsv(read(join(RAW, 'tatoeba-eng-vie.tsv'))));
const pairs = toItems(filtered.pairs, formIndex);
write(join(OUT, 'tatoeba-en-vi.json'), toJson(contentFile(
	{
		source: 'Tatoeba (https://tatoeba.org) per-language exports eng_sentences, vie_sentences and eng-vie_links, joined in tool/raw/tatoeba-eng-vie.tsv',
		license: 'CC BY 2.0 FR (https://creativecommons.org/licenses/by/2.0/fr/)',
		attribution: 'Sentences and translations from Tatoeba (https://tatoeba.org), by its contributors'
	},
	pairs
)));
console.log(`Tatoeba: ${filtered.input} pairs before filtering`);
for (const { step, removed, remaining } of filtered.steps) {
	console.log(`  - ${step}: removed ${removed}, ${remaining} left`);
}
const bands = new Map<string, number>();
for (const p of pairs) bands.set(String(p.ngsl_band_max), (bands.get(String(p.ngsl_band_max)) ?? 0) + 1);
console.log(`Tatoeba: ${pairs.length} pairs; ngsl_band_max distribution:`);
for (const key of [...bands.keys()].sort()) console.log(`  band ${key}: ${bands.get(key)}`);

// --- Pseudo-words -----------------------------------------------------------------------------
const ngslForms = new Set(formIndex.keys());
const dictionary = new Set(read(wordListPath).split('\n').map((w) => w.trim().toLowerCase()));
const exclude = parseExcludeList(read(join(TOOL, 'pseudowords-exclude.txt')));
const generated = generatePseudowords(PSEUDOWORD_COUNT, PSEUDOWORD_SEED, { ngsl: ngslForms, dictionary, exclude });
console.log(`Pseudo-words: ${generated.rejected.length} candidates rejected:`);
for (const { word, reason } of generated.rejected) console.log(`  ${word}: ${reason}`);
write(join(OUT, 'pseudowords.json'), toJson(contentFile(
	{
		source: `Generated by tool/prepare-content.ts (seed ${PSEUDOWORD_SEED}) from English phonotactic templates; filtered against NGSL 1.2 forms and the word-list npm package`,
		license: 'CC0 1.0 (generated for this project)',
		attribution: 'None required'
	},
	generated.words.map((form) => ({ form }))
)));
write(join(TOOL, 'pseudowords-review.txt'), generated.words.join('\n') + '\n');
